package org.rf.template.entities;

// Generated Dec 11, 2016 11:49:31 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.rf.template.constants.Constanta;
import org.rf.template.core.persistence.domain.UuidBasedCoreDomain;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "user_log", catalog = Constanta.SCHEMA)
public class UserLog extends UuidBasedCoreDomain implements
		java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -1252126827779771366L;
	private Date createdDate;
	private Users userAdmin;
	private Users user;
	private String action;

	public UserLog() {
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ADMIN_ID", nullable = true)
	public Users getUserAdmin() {
		return userAdmin;
	}

	public void setUserAdmin(Users userAdmin) {
		this.userAdmin = userAdmin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = true)
	public Users getUser() {
		return user;
	}

	public void setUser(Users user) {
		this.user = user;
	}

	@Column(name = "ACTION", length = 50)
	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

}
