package org.rf.template.entities;

// Generated Dec 11, 2016 11:49:31 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.rf.template.constants.Constanta;
import org.rf.template.core.persistence.domain.UuidBasedCoreDomain;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = Constanta.SCHEMA)
public class Users extends UuidBasedCoreDomain implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 3442262402591789906L;
	private Group group;
	private Role role;
	private String nama;
	private String userName;
	private String email;
	private String userPassword;
	private Date createdDate;
	private Date updatedDate;
	private Date lastLogin;
	private String aktif;
	private Users createdBy;
	private Users updatedBy;
	private String idReferensiHirarki;
	private String jenisHirarki;	

	public Users() {
	}

	public Users(Group group, Role role) {
		this.group = group;
		this.role = role;
	}

	public Users(Group group, Role role, String nama, String userName,
			String email, String userPassword, Date createdDate,
			Date updatedDate, Date lastLogin, String aktif) {
		this.group = group;
		this.role = role;
		this.nama = nama;
		this.userName = userName;
		this.email = email;
		this.userPassword = userPassword;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.lastLogin = lastLogin;
		this.aktif = aktif;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "GROUP_ID", nullable = true)
	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ROLE_ID", nullable = true)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "NAMA")
	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Column(name = "USER_NAME")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "EMAIL")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "USER_PASSWORD", length = 60)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_LOGIN", length = 19)
	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	@Column(name = "AKTIF")
	public String getAktif() {
		return aktif;
	}

	public void setAktif(String aktif) {
		this.aktif = aktif;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY", nullable = true)
	public Users getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Users createdBy) {
		this.createdBy = createdBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY", nullable = true)
	public Users getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Users updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "ID_REFERENSI_HIRARKI")
	public String getIdReferensiHirarki() {
		return idReferensiHirarki;
	}

	public void setIdReferensiHirarki(String idReferensiHirarki) {
		this.idReferensiHirarki = idReferensiHirarki;
	}

	@Column(name = "JENIS_HIRARKI")
	public String getJenisHirarki() {
		return jenisHirarki;
	}

	public void setJenisHirarki(String jenisHirarki) {
		this.jenisHirarki = jenisHirarki;
	}

}
